### PR TITLE
Streams/Laziness

### PR DESCRIPTION
**Pull request by kazetsukaimiko**
This one may seem like a distraction, but it looked simple enough to implement. Based off of new master, this adds `Stream<ENTITY>` methods to all the Daos for every operation returning more than one row.

More critically, it changes `SqlRunner.foldingSelect` to return `Stream<BUILDER>`. `KeylessDaoImpl.foldingSelect` is where the reduce operation (using the accumulator) has moved to.

No tests were changed to get this working, and all tests pass. I think I did switch RandomUtils to Stream by default as well, but that is unrelated.

I do apologize for getting off track. If we do manage to add support for range queries, buffering the entire dataset into memory is going to be a showstopper.

### CODE REVIEW

**Comment by ojplg** [comment]
I do not understand the purpose of this. It makes things more complicated. There's already a folding operation that allows you to work on large result sets without realizing an entire list of objects in memory.

**Comment by kazetsukaimiko** [comment]
I'm not sure how this makes things more complicated, at least architecturally. I'd like to  think I actually simplified the internals a bit overall... instead of doing your own accumulator and mapping operations, the code now leverages Stream, map, and reduce. foldingSelect was kind of a roll-your-own map reduce operation to begin with. I did add safeguards to ensure all resources close, and overall, less parameters are being passed to each function in sqlRunner.

My strongest argument here would be that the Streams API is going to be more universally familiar to developers than something like foldingSelect, and while both approaches accomplish the same thing, Stream is going to have all of its additional benefits.

I guess I'd concur on increased complexity when it comes to the additional interface methods, that does make things a little ugly. Perhaps they could be kept off the interface, and if the developer really wants access to them, he could cast to the implementation?

**Comment by ojplg** [comment]
Is it more complicated? In my mind, yes.
* There's more code.
* There's laziness.
 * There's now a problem with locality. Think about code like this:
  `Stream<Item> itemStream;`
   `try {`
    `      itemSteam = dao.lazySelect();`
    `} catch (HrormException ex){`
    `      doSpecialDatabaseErrorHandling(ex);`
    `}`
   `process(itemStream);`
   
   That will be sad for everyone.
 * Also makes ordering of outputs confusing. (Why monadic sequencing is such a big deal for Haskell IO)
  `Stream<Item> itemStream;`
  `System.out.println("Reading DB");`
  `itemStream = dao.lazySelect();`
  `System.out.println("Done reading DB");`
  `process(itemStream)` 

    Again, that is sad for everyone.
  * In general, it goes against the hrorm ethos: when you call a method, it does something. When you reach the next sequence point (semi-colon) everything is done. Hrorm is simple. Laziness is hard.
  * When will connections be closed? What if there's a pool? It's hard to know when things are done.

The current foldingSelect method is much more hrorm-y. It takes a bit of effort perhaps to figure it out, but anyone who has seen a fold will get it. And those that haven't will have to learn something.

**Comment by kazetsukaimiko** [comment]
I would say the examples provided are a little edgy. Those familiar with Streams are going to process them on the spot precisely because they're lazy. Same with ordering, the "I'm done" is typically going to happen after you consume the Stream, not before. Streams cannot be handled like Lists, they've never been intended to work that way.

That is a minor issue though in comparison to your core objection. I'll say, this has been a learning experience. Especially this:

_In general, it goes against the hrorm ethos: when you call a method, it does something. When you reach the next sequence point (semi-colon) everything is done._

I really do like this library, and no small part of that is due to the design decisions made. I was not thinking of hrorm method calls as a boundary after which you should expect all work to be done, so I didn't model the changes after that paradigm, I modelled them after what I thought would be ideal consumption interfaces. 

However if that immediately runs afowl of the design goals of the project then we're no longer working towards a common goal... regardless of whether I submitted this PR with good intentions. At the very least it is introducing inconsistency.

Lets reject this PR. My next one will be around the Keyless Operator tests. I'm wondering if you're open to expanding the README in GitHub- I know you have the website hrorm.org, but not sure how/if I could contribute to the documentation end of things aside from code comments.

**Comment by ojplg** [comment]
I will close this for now.

I will say, perhaps the examples I pointed out are "a little edgy", but that's one way computer programs get complicated and hard to understand. The small addition of things that work, and perhaps even work easily, but that you have to remember and keep track of.

It's a difference between an interface that is possible (and maybe easy) to use correctly, and one that is impossible (or at least difficult) to use incorrectly.

**Pull request closed without merging**
